### Update Patient data
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174003
Content-Type: application/json

{
  "name": "Bousy1",
  "email": "bousy_updated@gmail.com",
  "address": "New York main street near Vogue Cafe Studio",
  "dateOfBirth": "1903-09-23"
}

###